### PR TITLE
Feature : MultiSelect can be used as a controlled component (#156)

### PR DESCRIPTION
**Pull request by BaptWaels**
## Proposed Changes

  - Able to use the component as a controlled components

### CODE REVIEW

**Comment by BaptWaels** [comment]
I have no idea how to reduce my code number of lines... (codeclimate)

**Comment by yegor-babiy** [comment]
@BaptWaels thanks for your effort, but such fix doesn't work for all available component states, I mean when in selected area we have search bar

**Comment by yegor-babiy** [comment]
@BaptWaels thanks for your effort, 
I am also investigated such issue and find the same solution, like you.
@liorheber, checked all available component states, it works as expected
I think it's good candidate for merging.

**Comment by BaptWaels** [comment]
@yegor-babiy Alright, thanks. What should I do next ?

**Comment by yegor-babiy** [comment]
> @yegor-babiy Alright, thanks. What should I do next ?

waiting on @liorheber approval

**Comment by liorheber** [comment]
Thank you @BaptWaels !

**Comment by BaptWaels** [comment]
Great ! Thanks for the review @yegor-babiy @liorheber

**Pull request merged**
