### PR TITLE
fix : selected item is removed when it 's being filtered from the ava…

### LINKED ISSUE #98: selected item is removed when it 's being filtered from the available items and later click the select all
## Expected Behavior
selected item should not be removed if it doesn't exist in the filtered available items

## Actual Behavior
selected item is removed

## Steps to Reproduce the Problem

  1.select an item
  2.filter the item from the available items by providing the list with new items
  3. now select another item
  4. click the select all
  5. please notice that the first selected item was removed

## Specifications

  - Version: 1.0.56

### PR DESCRIPTION
**Pull request by essamor**
…ilable items and later click the select all

Fixes #98 

## Proposed Changes

-selection should also include items that were selected but not exist on the items (were filtered out) when click select all

### CODE REVIEW

**Comment by essamor** [comment]
@liorheber please review

**Comment by liorheber** [comment]
@talyak could you please review this PR?

**Comment by essamor** [comment]
@liorheber @talyak 
could you go over this ?

**Comment by talyak** [comment]
I am not sure this is the right solution for this case.
the component work well if you try to reproduce the issue in the storybook.
the problem occurred when you set new items outside from the component. 
I think before you set the new items outside of the component you should also set the selected items of it.
@liorheber - what do you think?

**Comment by essamor** [comment]
but i have no control over the select all from outside the component

**Comment by talyak** [comment]
if you will set correctly the selected items (as was before you set the new items) the component should work well.

**Comment by liorheber** [comment]
I understand what you're saying @talyak.
However, I would like the component to be self contained and avoid it's logic leaking to the consumer.
Why would the filter, which filters the source items only, effect the selected items and why should the application know about that?
I'm open to a discussion if i'm missing something.

**Comment by essamor** [comment]
@liorheber @talyak 
Do you have further comments ? could you merge ?

**Comment by talyak** [comment]
@essamor  - I still don't understand why it is not working for you. if you changed the items, why the selected Items changed? the newSelectedItem contains all the previous selected items and the filtered. why the previous selected item disappeared from this list?

**Comment by essamor** [comment]
they disappear because they don't exist in the items

**Pull request merged**
