### PR TITLE
Default messages and custom icons

### PR DESCRIPTION
**Pull request by AmirAsaraf**
1) default messages
2) custom icons
3) remove errors

image

### CODE REVIEW

**Comment by liorheber** [comment]
Great!
Can you update the readme to include the new props?
Also need some documentation of the strings we support.

**Comment by AmirAsaraf** [comment]
@liorheber I'm doing it right now. Also changing some props. some unrelevant

**Comment by liorheber** [comment]
ready for merge?

**Comment by AmirAsaraf** [comment]
yup

**Pull request merged**
