### PR TITLE
updated to babel7, use webpack extract plugin to create separate style.css file

### PR DESCRIPTION
**Pull request by jorgemmsilva**
## Proposed Changes

  - update to babel7
  - use webpack extract plugin to create separate style.css file

Reasoning for the separate css file change is that the current implementation breaks when trying to render the component on tests (using enzyme or react-test-renderer) with: 
`TypeError: target.appendChild is not a function`
This is because style-loader tries to append a `<style>` tag to a DOM element that does not exist.

Extracting the css logic to a separate file fixes this issue.

**Caution: this is a breaking change - users updating to this version need to import the css file separately on their app**

### What could be Improved

 - minify the css file

### CODE REVIEW

**Comment by jorgemmsilva** [comment]
(no idea why the `id` prop changed from 1 to 3 on the snapshots ¯\_(ツ)_/¯ )

**Comment by liorheber** [comment]
Hi @jorgemmsilva, thank you for your contribution!
We will be reviewing your PR today and we look forward for this addition.

**Comment by liorheber** [comment]
Please notice that this project is managed using yarn and not npm.
While newer versions of yarn support package.lock at this point we expect yarn.lock to contain our dependencies versions.
Please make this change with yarn instead of npm.

Thanks!

**Comment by liorheber** [comment]
@jorgemmsilva sorry for the delay.
I went over the PR and overall great work and an important update!

1. Please update the readme to indicate users that they should import the style.css to use the project.
2. Please amend your commit message to use BREAKING CHANGE so that we increment our version to indicate the breaking change.
We use semantic-release for our versioning so you can have a look [here](https://github.com/semantic-release/semantic-release).
3. The yarn.lock is conflicted with the master version.

Thanks again!

**Comment by jorgemmsilva** [comment]
@liorheber should be good to go :)

**Comment by liorheber** [comment]
Thank you for your contribution! :)

**Pull request merged**
