### PR TITLE
Throws warning: List doesn't get rendered when items are loaded async and select component is hidden

### LINKED ISSUE #143: List doesn't get rendered when items are loaded async and select component is hidden
I load the items for the multi select component asynchonously and the component is hidden at render time.

## Expected Behavior
Items render normally

## Actual Behavior
Items don't render

## Steps to Reproduce the Problem
Just set the items variable asynchonously and set display none of component
Here's a reproduction setup (i use bootstrap tab for simplicity, but it should be equivalent to the setup i described): https://codesandbox.io/s/94nlm5mjrr

## Specifications
  - Version: v1.0.73
  - Platform: Chrome/Ubuntu 18
  - Subsystem:

My guess is that at render time, due that the component is not visible, it has no actual height. And because this package uses "react-height" i think that might be the problem.

### PR DESCRIPTION
**Pull request by yegor-babiy**
Fixes #143

## Proposed Changes

  - removed react-height package
  - replace approach with usage react-height
  - updated related snapshot

### CODE REVIEW

**Comment by stepovat** [comment]
changed title to "breaking changes", with "s" in the end - otherwise release won't be triggered

**Comment by stepovat** [comment]
Please check the inputs from "codeclimate/total-coverage"

**Comment by liorheber** [comment]
Why is this a breaking change? It has no effect on the API of the component as far as I see.

**Comment by yegor-babiy** [comment]
> Why is this a breaking change? It has no effect on the API of the component as far as I see.

you are right, which changes I should made in PR?

**Comment by yegor-babiy** [comment]
Please don't merge, got issue with React.createRef(), checking...

**Comment by stepovat** [comment]
@yegor-babiy changing the title is enough :)

**Comment by liorheber** [comment]
Not the title, need to ammend the commit message

**Comment by yegor-babiy** [comment]
Issue was fixed,
PS, we lost 0.5% coverage because I can't mock divHTMLElement object, as I am using clientHeight property from there.

Do we have ability to merge branch?
I suggest to do it and will try to improve test coverage during the sprint as I have more priority tasks

And which message is correct for commit?

**Comment by yegor-babiy** [comment]
@liorheber, what do you think? can be merged?

**Comment by stepovat** [comment]
@liorheber if no objections, I will merge in the evening

**Pull request merged**
