### PR TITLE
export default components

### PR DESCRIPTION
**Pull request by sabativi**
## Proposed Changes

  - export default components so that we can compose behaviours based on them

## Notes

I have huge difficulties running this locally, I tried to install an npm package to show reorder of elems but it crash, I thought it was a node version problem but apparently not.

I have tried to install the package locally from another project but I have a "window is undefined".

So I propose to merge this PR, build the package so that I can install it and make an example with sortable-js.

### CODE REVIEW

**Comment by liorheber** [comment]
Thanks for looking into this feature!

@sabativi it sounds a bit critical that you're having issues using the component.
Could I ask that you share a bit more information on the issue you're receiving? 
The stack trace of the error? How you used the component when it failed etc.?

As for this PR, if you need the default component to get this feature to work, doesn't it mean that it will break for someone who's using their own renderer for the component?
Seems to me that the solution needs to be a bit more generic.

**Comment by sabativi** [comment]
The 'window' is not defined problem was a mistake from I.

I will try to integrate with https://github.com/clauderic/react-sortable-hoc as it says that it works with react-virtualized which is used by this module.

Will keep you updated

**Comment by liorheber** [comment]
Great news, thanks!

**Comment by talyak** [comment]
@sabativi - Can I close this PR?

**Comment by sabativi** [comment]
Yes

**Pull request closed without merging**
